name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          # Build ulang tanpa cache agar settingan port di main/resources terbawa
          docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-deploy-student7-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-deploy-student7-app:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            mkdir -p /home/student/spring-app/student7
            cd /home/student/spring-app/student7
            
            # 1. Hapus container lama secara paksa agar port 9077 terlepas
            docker rm -f spring-deploy-student7-app || true
            
            # 2. Buat network jika belum ada (antisipasi error mentor)
            docker network create classroom_classroom_net || true
            
            # 3. Buat file .env
            echo "APP_PORT=9077" > .env
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env

            # 4. Tulis file docker-compose.yml
            echo "services:
              spring-deploy-student7-app:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/spring-deploy-student7-app:latest
                container_name: spring-deploy-student7-app
                ports:
                  - '9077:9077'
                env_file:
                  - .env
                restart: always
                networks:
                  - classroom_classroom_net

            networks:
              classroom_classroom_net:
                external: true" > docker-compose.yml
            
            # 5. Eksekusi
            docker compose pull
            docker compose up -d
            
            # 6. Intip log 5 detik pertama untuk pastikan tidak crash
            sleep 5
            docker logs --tail 20 spring-deploy-student7-app